// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOatncA5uBoI2XCv-9fVTnsim_l2zIzK0',
    appId: '1:1069702495258:web:e651e83ad9d7901a1825a3',
    messagingSenderId: '1069702495258',
    projectId: 'home-care-nursing-e733e',
    authDomain: 'home-care-nursing-e733e.firebaseapp.com',
    storageBucket: 'home-care-nursing-e733e.firebasestorage.app',
    measurementId: 'G-B2RR7NXH4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkvoHVx4MLZKZL5iGRbHkGB6LzXAAfqiI',
    appId: '1:1069702495258:android:6dc088a9d7ef2f301825a3',
    messagingSenderId: '1069702495258',
    projectId: 'home-care-nursing-e733e',
    storageBucket: 'home-care-nursing-e733e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49j1VvZMeBtJw2mLvvaoWNzubj1b5tu0',
    appId: '1:1069702495258:ios:a71f603ee6e464331825a3',
    messagingSenderId: '1069702495258',
    projectId: 'home-care-nursing-e733e',
    storageBucket: 'home-care-nursing-e733e.firebasestorage.app',
    iosBundleId: 'com.homecare.homecareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49j1VvZMeBtJw2mLvvaoWNzubj1b5tu0',
    appId: '1:1069702495258:ios:a71f603ee6e464331825a3',
    messagingSenderId: '1069702495258',
    projectId: 'home-care-nursing-e733e',
    storageBucket: 'home-care-nursing-e733e.firebasestorage.app',
    iosBundleId: 'com.homecare.homecareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOatncA5uBoI2XCv-9fVTnsim_l2zIzK0',
    appId: '1:1069702495258:web:51964af74acb54111825a3',
    messagingSenderId: '1069702495258',
    projectId: 'home-care-nursing-e733e',
    authDomain: 'home-care-nursing-e733e.firebaseapp.com',
    storageBucket: 'home-care-nursing-e733e.firebasestorage.app',
    measurementId: 'G-QYK1TDZGZ3',
  );
}
